// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __UserManager_h__
#define __UserManager_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CallSystem
{

class UserManager;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CallSystem::UserManager>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CallSystem::UserManager*);

}

}

namespace CallSystem
{

class UserManager;
bool operator==(const UserManager&, const UserManager&);
bool operator<(const UserManager&, const UserManager&);
::Ice::Object* upCast(::CallSystem::UserManager*);
typedef ::IceInternal::Handle< ::CallSystem::UserManager> UserManagerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CallSystem::UserManager> UserManagerPrx;
void __patch(UserManagerPtr&, const ::Ice::ObjectPtr&);

}

namespace CallSystem
{

class Callback_UserManager_darAlta_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserManager_darAlta_Base> Callback_UserManager_darAltaPtr;

class Callback_UserManager_comprarMinutos_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserManager_comprarMinutos_Base> Callback_UserManager_comprarMinutosPtr;

class Callback_UserManager_avisarConsumo_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserManager_avisarConsumo_Base> Callback_UserManager_avisarConsumoPtr;

class Callback_UserManager_connect_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserManager_connect_Base> Callback_UserManager_connectPtr;

class Callback_UserManager_disconnect_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_UserManager_disconnect_Base> Callback_UserManager_disconnectPtr;

}

namespace IceProxy
{

namespace CallSystem
{

class UserManager : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int darAlta(::Ice::Int dni)
    {
        return darAlta(dni, 0);
    }
    ::Ice::Int darAlta(::Ice::Int dni, const ::Ice::Context& __ctx)
    {
        return darAlta(dni, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_darAlta(::Ice::Int dni, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_darAlta(dni, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_darAlta(::Ice::Int dni, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_darAlta(dni, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_darAlta(::Ice::Int dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_darAlta(dni, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_darAlta(::Ice::Int dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_darAlta(dni, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_darAlta(::Ice::Int dni, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_darAlta(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_darAlta(dni, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni)
    {
        return begin_darAlta(dni, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni, const ::Ice::Context& __ctx)
    {
        return begin_darAlta(dni, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_darAlta(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_darAlta(dni, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni, const ::CallSystem::Callback_UserManager_darAltaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_darAlta(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int dni, const ::Ice::Context& __ctx, const ::CallSystem::Callback_UserManager_darAltaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_darAlta(dni, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_darAlta(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int darAlta(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_darAlta(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int comprarMinutos(::Ice::Int dni, ::Ice::Int minutos)
    {
        return comprarMinutos(dni, minutos, 0);
    }
    ::Ice::Int comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx)
    {
        return comprarMinutos(dni, minutos, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_comprarMinutos(dni, minutos, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_comprarMinutos(dni, minutos, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_comprarMinutos(dni, minutos, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_comprarMinutos(dni, minutos, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_comprarMinutos(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_comprarMinutos(dni, minutos, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos)
    {
        return begin_comprarMinutos(dni, minutos, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx)
    {
        return begin_comprarMinutos(dni, minutos, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_comprarMinutos(dni, minutos, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_comprarMinutos(dni, minutos, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::CallSystem::Callback_UserManager_comprarMinutosPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_comprarMinutos(dni, minutos, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int dni, ::Ice::Int minutos, const ::Ice::Context& __ctx, const ::CallSystem::Callback_UserManager_comprarMinutosPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_comprarMinutos(dni, minutos, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_comprarMinutos(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip)
    {
        return avisarConsumo(dni, minutesAlertThreshold, myip, 0);
    }
    ::Ice::Int avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx)
    {
        return avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_avisarConsumo(dni, minutesAlertThreshold, myip, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_avisarConsumo(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::CallSystem::Callback_UserManager_avisarConsumoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int dni, ::Ice::Int minutesAlertThreshold, const ::std::string& myip, const ::Ice::Context& __ctx, const ::CallSystem::Callback_UserManager_avisarConsumoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_avisarConsumo(dni, minutesAlertThreshold, myip, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_avisarConsumo(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int connect(const ::std::string& myip, const ::std::string& port)
    {
        return connect(myip, port, 0);
    }
    ::Ice::Int connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx)
    {
        return connect(myip, port, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_connect(const ::std::string& myip, const ::std::string& port, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_connect(myip, port, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_connect(const ::std::string& myip, const ::std::string& port, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_connect(myip, port, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_connect(myip, port, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_connect(myip, port, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_connect(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_connect(myip, port, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port)
    {
        return begin_connect(myip, port, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx)
    {
        return begin_connect(myip, port, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_connect(myip, port, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_connect(myip, port, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port, const ::CallSystem::Callback_UserManager_connectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_connect(myip, port, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_connect(const ::std::string& myip, const ::std::string& port, const ::Ice::Context& __ctx, const ::CallSystem::Callback_UserManager_connectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_connect(myip, port, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_connect(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int connect(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_connect(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int disconnect(const ::std::string& myip)
    {
        return disconnect(myip, 0);
    }
    ::Ice::Int disconnect(const ::std::string& myip, const ::Ice::Context& __ctx)
    {
        return disconnect(myip, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_disconnect(const ::std::string& myip, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_disconnect(myip, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_disconnect(const ::std::string& myip, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_disconnect(myip, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_disconnect(const ::std::string& myip, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_disconnect(myip, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_disconnect(const ::std::string& myip, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_disconnect(myip, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_disconnect(const ::std::string& myip, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_disconnect(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_disconnect(myip, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip)
    {
        return begin_disconnect(myip, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip, const ::Ice::Context& __ctx)
    {
        return begin_disconnect(myip, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_disconnect(myip, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_disconnect(myip, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip, const ::CallSystem::Callback_UserManager_disconnectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_disconnect(myip, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string& myip, const ::Ice::Context& __ctx, const ::CallSystem::Callback_UserManager_disconnectPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_disconnect(myip, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_disconnect(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int disconnect(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_disconnect(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<UserManager> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_secure(bool __secure) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_twoway() const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_oneway() const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_batchOneway() const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_datagram() const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_batchDatagram() const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_compress(bool __compress) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_timeout(int __timeout) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<UserManager> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<UserManager*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace CallSystem
{

class UserManager : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Int darAlta(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int connect(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int disconnect(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace CallSystem
{

class UserManager : virtual public ::IceDelegate::CallSystem::UserManager,
                    virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Int darAlta(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int connect(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int disconnect(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace CallSystem
{

class UserManager : virtual public ::IceDelegate::CallSystem::UserManager,
                    virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Int darAlta(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int connect(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int disconnect(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace CallSystem
{

class UserManager : virtual public ::Ice::Object
{
public:

    typedef UserManagerPrx ProxyType;
    typedef UserManagerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Int darAlta(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___darAlta(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int comprarMinutos(::Ice::Int, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___comprarMinutos(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int avisarConsumo(::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___avisarConsumo(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int connect(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___connect(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int disconnect(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___disconnect(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const UserManager& l, const UserManager& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const UserManager& l, const UserManager& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CallSystem
{

template<class T>
class CallbackNC_UserManager_darAlta : public Callback_UserManager_darAlta_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_UserManager_darAlta(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_darAlta(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserManager_darAltaPtr
newCallback_UserManager_darAlta(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_darAlta<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserManager_darAltaPtr
newCallback_UserManager_darAlta(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_darAlta<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserManager_darAlta : public Callback_UserManager_darAlta_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_UserManager_darAlta(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_darAlta(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserManager_darAltaPtr
newCallback_UserManager_darAlta(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_darAlta<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserManager_darAltaPtr
newCallback_UserManager_darAlta(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_darAlta<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_UserManager_comprarMinutos : public Callback_UserManager_comprarMinutos_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_UserManager_comprarMinutos(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_comprarMinutos(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserManager_comprarMinutosPtr
newCallback_UserManager_comprarMinutos(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_comprarMinutos<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserManager_comprarMinutosPtr
newCallback_UserManager_comprarMinutos(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_comprarMinutos<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserManager_comprarMinutos : public Callback_UserManager_comprarMinutos_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_UserManager_comprarMinutos(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_comprarMinutos(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserManager_comprarMinutosPtr
newCallback_UserManager_comprarMinutos(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_comprarMinutos<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserManager_comprarMinutosPtr
newCallback_UserManager_comprarMinutos(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_comprarMinutos<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_UserManager_avisarConsumo : public Callback_UserManager_avisarConsumo_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_UserManager_avisarConsumo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_avisarConsumo(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserManager_avisarConsumoPtr
newCallback_UserManager_avisarConsumo(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_avisarConsumo<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserManager_avisarConsumoPtr
newCallback_UserManager_avisarConsumo(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_avisarConsumo<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserManager_avisarConsumo : public Callback_UserManager_avisarConsumo_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_UserManager_avisarConsumo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_avisarConsumo(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserManager_avisarConsumoPtr
newCallback_UserManager_avisarConsumo(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_avisarConsumo<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserManager_avisarConsumoPtr
newCallback_UserManager_avisarConsumo(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_avisarConsumo<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_UserManager_connect : public Callback_UserManager_connect_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_UserManager_connect(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_connect(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserManager_connectPtr
newCallback_UserManager_connect(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_connect<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserManager_connectPtr
newCallback_UserManager_connect(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_connect<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserManager_connect : public Callback_UserManager_connect_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_UserManager_connect(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_connect(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserManager_connectPtr
newCallback_UserManager_connect(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_connect<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserManager_connectPtr
newCallback_UserManager_connect(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_connect<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_UserManager_disconnect : public Callback_UserManager_disconnect_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_UserManager_disconnect(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_disconnect(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_UserManager_disconnectPtr
newCallback_UserManager_disconnect(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_disconnect<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_UserManager_disconnectPtr
newCallback_UserManager_disconnect(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_UserManager_disconnect<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_UserManager_disconnect : public Callback_UserManager_disconnect_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_UserManager_disconnect(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::CallSystem::UserManagerPrx __proxy = ::CallSystem::UserManagerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_disconnect(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_UserManager_disconnectPtr
newCallback_UserManager_disconnect(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_disconnect<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_UserManager_disconnectPtr
newCallback_UserManager_disconnect(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_UserManager_disconnect<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
